app_index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

app_play:
    path: /play/{id}
    defaults:  { _controller: AppBundle:Default:play }
    requirements:
        id: \d+

user_registration:
    path: /registrer
    defaults: { _controller: AppBundle:User:registrer }

user_login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

user_login_check:
    path: /login_check

user_logout:
    path: /logout

user_account:
    path: /user/account
    defaults: { _controller: AppBundle:User:account }

stream_edit:
    path: /stream/edit/{id}
    defaults:  { _controller: AppBundle:Stream:edit }
    requirements:
        id: \d+

test_mail:
    path: /mail/test
    defaults:  { _controller: AppBundle:Default:testMail }