AppBundle\Entity\User:
    type: entity
    table: user
    indexes:
        fk_users_watchlist1_idx:
            columns:
                - watchlist_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        salt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
    manyToOne:
        watchlist:
            targetEntity: Watchlist
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                watchlist_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
