AppBundle\Entity\Watchlist:
    type: entity
    table: watchlist
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToMany:
        videos:
            targetEntity: Videos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: watchlist
            joinTable:
                name: watchlist_has_videos
                joinColumns:
                    -
                        name: watchlist_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: videos_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
